---
title: "Airbnb Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(janitor)
library(viridis)

library(plotly)

library(shiny)
```

```{r import_data}
airbnb_data = read.csv("https://people.bu.edu/kalathur/datasets/nyc_airbnb.csv") %>%
  clean_names() %>%
  rename(boro = neighbourhood_group) %>% 
  mutate(rating = review_scores_location / 2) %>% 
  filter(!is.na(rating)) 

```

Column {.sidebar}
-----------------------------------------------------------------------
This `flexdashboard` with Shiny was made for [Jeff Goldsmith's Data Science I class](http://jeffgoldsmith.com/DSI/index.html) in the Department of Biostatistics at Columbia University. The data come from [Inside Airbnb](http://insideairbnb.com/about.html), which provides Airbnb data from different cities, and this dashboard focuses on NYC. Download the data used for this app [here](http://jeffgoldsmith.com/DSI/dataset_airbnb.html).

```{r}
boros = airbnb_data %>% distinct(boro) %>% pull()

# selectInput widget
selectInput("boro_choice", label = h3("Select boro"),
            choices = boros, selected = "Manhattan")

hr()

## sliderInput widget
# set min and max price based on boro choice
renderUI({
  max_price = airbnb_data %>% filter(boro == input$boro_choice) %>% 
                           distinct(price) %>% max()
  
  min_price = airbnb_data %>% filter(boro == input$boro_choice) %>% 
                           distinct(price) %>% min()
  
  sliderInput("price_range", label = h3("Choose price range"), min = min_price, 
        max = max_price, value = c(100, 400))
})

hr()

room_choice = airbnb_data %>% distinct(room_type) %>% pull()

# radioButtons widget
radioButtons("room_choice", label = h3("Choose room type"),
    choices = room_choice, 
    selected = "Entire home/apt")

```

Row 
-----------------------------------------------------------------------

### Airbnb prices by location

```{r}
renderPlotly({
    airbnb_data %>%
    filter(boro == input$boro_choice, 
           price %in% input$price_range[1]:input$price_range[2],
           room_type == input$room_choice) %>%
    mutate(text_label = str_c("Price: $", price, '\nRating: ', rating)) %>% 
    plot_ly(x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~price,
          text = ~text_label)
})

```

Row {.tabset .tabset-fade } 
-----------------------------------------------------------------------

### Neighborhood popularity

```{r}

x <- list(
  title = "",
  tickangle = 40,
  tickfont = list(
    size = 8  
  )
)

y <- list(
  title = "number of listings"
)


renderPlotly({
  airbnb_data %>% 
        filter(boro == input$boro_choice, 
           price %in% input$price_range[1]:input$price_range[2],
           room_type == input$room_choice) %>%
    count(neighbourhood) %>% 
    mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
    plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar") %>%
      layout(xaxis = x, yaxis = y)
})
```

### Prices for most popular neighborhoods

```{r}
renderPlotly({ 
  common_neighborhoods =
    airbnb_data %>% 
    filter(boro == input$boro_choice,
           price %in% input$price_range[1]:input$price_range[2],
           room_type == input$room_choice) %>%
    count(neighbourhood, sort = TRUE) %>% 
    top_n(8) %>% 
    select(neighbourhood)

  airbnb_data %>%
    filter(boro == input$boro_choice,
                          price %in% input$price_range[1]:input$price_range[2],
                          room_type == input$room_choice) %>%
    inner_join(., common_neighborhoods, by = "neighbourhood") %>% 
    plot_ly(y = ~price, color = ~neighbourhood, type = "box",
          colors = "Set2") %>%
    layout(xaxis = x)
  
})

```

