df1 <- read.csv("/Users/haowu/Desktop/Boston University Graduate Study/CS 555/assignment1/hospital.csv",header = FALSE)
typeof(df1)
df1_num <- as.numeric(unlist(df1))
hist(df1_num, main="histogram of the duration of days", xlab = "Days", ylab = "Patients", Col = "grey", border = "black", freq = TRUE, breaks = seq(0,15, by=1))
library(psych)
df2 <- describe(df1_num, skew =TRUE)
df3 <- as.list(summary(df1_num))
df4 <- do.call(c,list(df2['sd'],df2['skew'],df2['range'],df3))
write.csv(df4, file ="Statistic Summary of Dataset2.csv")
pnorm(10,mean = 5, sd = 3)
pnorm(10,mean = 5, sd = 3) - pnorm(3, mean = 5, sd = 3)
