    
SELECT OrderNo, OrderDate, Amount FROM BOSTON_PAPER.PAPER_ORDER WHERE CName = 'Jia';
SELECT EmpNo,EmpName FROM BOSTON_PAPER.EMPLOYEE WHERE (SELECT count(*) FROM BOSTON_PAPER.HANDLES WHERE EmpNo ) >= 2;
SELECT BrNo, Address, Phone FROM BOSTON_PAPER.BRANCH WHERE CName = 'Hao';
SELECT OrderNo,SuborderNo,RqshipDate,ActShipDate FROM BOSTON_PAPER.SUBORDER WHERE RqshipDate < ActShipDate ;
SELECT CName, BrNo, Address, Phone FROM BOSTON_PAPER.BRANCH WHERE CName in (SELECT CName FROM BOSTON_PAPER.SUBORDER WHERE ActShipDate = '2000-02-19');
