CREATE DATABASE BOSTON_PAPER;
CREATE TABLE BOSTON_PAPER.CUSTOMER	
	(CName				VARCHAR(15)   					NOT NULL,
	 Phone				CHAR(9)					 		NOT NULL,
	 Address			VARCHAR(30),
	PRIMARY KEY (CName));
CREATE TABLE BOSTON_PAPER.PAPER_ORDER
	(OrderNo			INT								NOT NULL,
	 OrderDate			DATE,						
	 Amount				DECIMAL(10,2)         			NOT NULL,
     CName				VARCHAR(15)						NOT NULL,
	PRIMARY KEY(OrderNo),
    FOREIGN KEY (CName) REFERENCES CUSTOMER(Cname) );
CREATE TABLE BOSTON_PAPER.BRANCH
	(CName				VARCHAR(15)						NOT NULL,
	 BrNo				CHAR(10)						NOT NULL,
	 Phone				CHAR(9),
	 Address			VARCHAR(30),
	PRIMARY KEY(Brno),
	FOREIGN KEY (CName) REFERENCES CUSTOMER (CName) );
CREATE TABLE BOSTON_PAPER.SUBORDER	
	(OrderNo			INT 						NOT NULL,        
	 CName			    VARCHAR(15)					NOT NULL,
	 SuborderNo			INT						    NOT NULL,
	 RqshipDate 		DATE,
	 ActShipDate		DATE,
     BrNo				CHAR(10)					NOT NULL,
	PRIMARY KEY( SuborderNo),
	FOREIGN KEY (OrderNo) REFERENCES PAPER_ORDER (OrderNo) ,
    FOREIGN KEY (CName  ) REFERENCES BRANCH (CName),
    FOREIGN KEY (BrNo) REFERENCES BRANCH (BrNo) );
CREATE TABLE BOSTON_PAPER.EMPLOYEE
	(EmpNo				INT							NOT NULL,
	 EmpName			VARCHAR(15)					NOT NULL,	
     Address			VARCHAR(30),
	 DOB				DATE,
	 Salary				DECIMAL(10,2)				NOT NULL,
	 Class  			VARCHAR(15),
	PRIMARY KEY(EmpNo) );
CREATE TABLE BOSTON_PAPER.HANDLES
	(EmpNo				INT							NOT NULL,
	 OrderNo			INT							NOT NULL,
	PRIMARY KEY( EmpNo, OrderNo),
	FOREIGN KEY (OrderNo) REFERENCES PAPER_ORDER (OrderNo),
	FOREIGN KEY (EmpNo) REFERENCES  EMPLOYEE( EmpNo) );
CREATE TABLE BOSTON_PAPER.PAPER
	(TypeNo				INT							NOT NULL,
	 Size				INT,
	 Weight				DECIMAL(5,1),
	 UnitPrice			DECIMAL(3,1)				NOT NULL, 
	PRIMARY KEY(TypeNo) );
CREATE TABLE BOSTON_PAPER.ORDER_ITEM
	(TypeNo 			INT						NOT NULL,
	 OrderNo			INT						NOT NULL,
	 SuborderNo			INT,
	 Quantity			CHAR(9),
	FOREIGN KEY (OrderNo) REFERENCES PAPER_ORDER (OrderNo),
	FOREIGN KEY (SuborderNo) REFERENCES SUBORDER (SuborderNo),
	FOREIGN KEY (TypeNo) REFERENCES PAPER (TypeNo) );
    






    




